include: package:flutter_lints/flutter.yaml

linter:
  rules:
    file_names: false   # camelCase file names allow karo

analyzer:
  errors:
    deprecated_member_use: ignore   # withOpacity, activeColor jaisi warnings ignore karo
